name: statstables-dev
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  # Add any other dependencies you need for your project
  - pip:
    - statsmodels
    - linearmodels
    - stargazer
  